### ISSUE TITLE
File attachments via form-data/multipart

### ISSUE THREAD

**Issue by davesheldon** [davesheldon/nap#13]
Usage:
```yaml
headers:
  Content-Type: multipart/form-data
files:
  - name: my-file.txt
    path: /path/to/my-file.txt
```
